
services:
   db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Bancos*1999
      - MYSQL_DATABASE=data_pets
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-u","root","-pBancos*1999"]
      timeout: 10s
      retries: 5
      interval: 10s
    ports: 
       - "3307:3306"

   frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
     target: prod
    ports:
      - "80:80"
    depends_on:
      - backend

   backend:
     build: 
      context: ./backend
      dockerfile: Dockerfile
     container_name: backend_pets
     ports:
      - "8000:8000"
     environment:
      - DATABASE=mysql+pymysql://root:Bancos*1999@db:3306/data_pets
     depends_on:
       db:
         condition: service_healthy

volumes:
  db_data:
